### ISSUE TITLE
Update Endless Sky source

### ISSUE THREAD

**Issue by OcelotWalrus** [quyykk/plugin-editor#2]
The problem with the map editor is that the map and some textures and other things from more recent Endless Sky release are not in. Could you update your branch where is stored all that files?

If I'm right it's this branch https://github.com/quyykk/endless-sky/tree/d06a57a13a00a8dd1557f429eb30260d6ba35bc0

**Comment by quyykk** [comment]
I've updated the branch to v0.10.2. However, that's all that I've done. Some things from v0.10.2 (like new attributes) haven't been implemented yet.

**Comment by OcelotWalrus** [comment]
Nice!

**Comment by TheGiraffe3** [comment]
[sorry if this is the wrong place to put this]
With 0.10.5 out and adding new CCOR systems, the source needs to be updated again. Could you do that?

**Comment by bene-dictator** [comment]
Quyykk has been inactive with ES development for much of this year so far – I wouldn't expect it to be done in the near future.
