### ISSUE TITLE
[Bug] Editor opens without a system window

### ISSUE THREAD

**Issue by Pshy0** [quyykk/plugin-editor#3]
**Bug Description**
When I open the editor, it is missing a system window (it's borderless), making it impossible to move or resize.

**Screenshot** of the editor opened from and over a terminal:
![image](https://github.com/quyykk/plugin-editor/assets/44928041/73567bdc-78d2-4278-b602-6f76b8cac468)

**Commit:** ef3478694a8a8a6e054020fd663d7c4a3a559717 (continuous builds)

**My system:** I use Ubuntu 23.04

**Comment by OcelotWalrus** [comment]
Maybe that your executable file don't have the right permissions? Try
`chmod +x <executable>`
Where <executable> is the path of your executable.

**Comment by OcelotWalrus** [comment]
What do you mean by a 'system window'. Are you talking about the pop-up to edit the systems?

**Comment by Pshy0** [comment]
> What do you mean by a 'system window'. Are you talking about the pop-up to edit the systems?

What allows me to move the editor window around on my desktop or resize it. It is missing.

**Comment by OcelotWalrus** [comment]
Ooh I see.

It seems weird because for me the window is always fullscreen. I think that's your problem: it does not start in fullscreen.

**Comment by quyykk** [comment]
> Actually the software is supposed to start in fullscreen and always stay fullscreen.

it uses the same preference as the game. You can press F11 to toggle

**Comment by quyykk** [comment]
@Pshy0 Can you test with the latest version again? Should be fixed now

**Comment by quyykk** [comment]
rip. Can you try again with the latest version?

**Comment by Pshy0** [comment]
> rip. Can you try again with the latest version?

![image](https://github.com/quyykk/plugin-editor/assets/44928041/14df6d1c-c0c7-4653-a46c-4522676afd04)

**Comment by quyykk** [comment]
Now try again :smile:

**Comment by Pshy0** [comment]
![image](https://github.com/quyykk/plugin-editor/assets/44928041/575170ed-703a-4dd3-90c1-8319d68540d6)
😭

**Comment by quyykk** [comment]
OK I gave up getting it to work on Wayland. It's fixed now

**Comment by Pshy0** [comment]
You have an option to close issues as not completed.

**Comment by quyykk** [comment]
But I fixed it :)

**Comment by Pshy0** [comment]
![image](https://github.com/quyykk/plugin-editor/assets/44928041/27b5854b-4dba-44a9-8e0e-b8d0c7dc8106)
 :>
