### ISSUE TITLE
[BUG/FEATURE REQUEST] Government Map Color

### ISSUE THREAD

**Issue by OcelotWalrus** [quyykk/plugin-editor#4]
I've noticed one thing:

#### Explanation
In plugins, you can create the `color` definition (it's basically a way to create a color under a name so you don't have to repeat the color code again and again so you just have to paste the name).

#### Issue
The issue: When you set a government color to a `color` definition instead of a color code, in the map the government is blank. But when you test it in the game, it's no blank.

#### Solution
Implement the `color` definition to government map color or something like that.

#### Example of use:
Simple example of use of the color definition
```
color "governments: Free"
    .25 .478 .145

government "Free Wolrd"
    color "governments: Free"

government "Militia"
    color "governments: Free"
```

**Comment by Pshy0** [comment]
This may just be the endless-sky sub-repository being outdated.
![image](https://github.com/quyykk/plugin-editor/assets/44928041/73ed8e79-b3a7-4991-a8c0-3df066a3a353)

**Comment by quyykk** [comment]
> This may just be the endless-sky sub-repository being outdated.

Yup, exactly

**Comment by OcelotWalrus** [comment]
Yes.
So if you update the endless-sky sub-repository, it will also add all new stuff on the mpa like Gegno and other stuff.

**Comment by OcelotWalrus** [comment]
Could you take care of updating it right now if it's okay for you? It would be nice.

**Comment by quyykk** [comment]
I can't unfortunately, I don't have my laptop with me right now. Probably next week unfortunately. Hopefully

**Comment by OcelotWalrus** [comment]
Okay, thanks anyway!

**Comment by OcelotWalrus** [comment]
> I can't unfortunately, I don't have my laptop with me right now. Probably next week unfortunately. Hopefully

And what about now?

**Comment by OcelotWalrus** [comment]
> I can't unfortunately, I don't have my laptop with me right now. Probably next week unfortunately. Hopefully

@quyykk 
And what about now?
Maybe you should add a github action to automatically update the sub-modules. So problems like this won't happen in the future.

**Comment by Pshy0** [comment]
> > I can't unfortunately, I don't have my laptop with me right now. Probably next week unfortunately. Hopefully
> 
> @quyykk And what about now? Maybe you should add a github action to automatically update the sub-modules. So problems like this won't happen in the future.

The sub-repository is not just endless-sky, it's a fork that is divergent. And it does not auto-merge.

**Comment by OcelotWalrus** [comment]
Ooh I see.
