### ISSUE TITLE
[BUG] Searching a system with its exact name gives no suggestion

### ISSUE THREAD

**Issue by Pshy0** [quyykk/plugin-editor#5]
## Bug description
If I look for a system by entering it's name correctly, it does not show in the suggestion list.

This could give the impression that the searched system does not exist while it does. pressing enter will load that system.

## Screenshots
- "So": Sol and Sol Arach are listed
![image](https://github.com/quyykk/plugin-editor/assets/44928041/88ddcdac-7b42-42ca-80a0-1ab6afbdf085)
- "Sol": Sol is no longer listed
![image](https://github.com/quyykk/plugin-editor/assets/44928041/25fa5f0a-68f5-419b-8cae-75f695296d56)
- "Sol " (with a space): Sol is listed again
![image](https://github.com/quyykk/plugin-editor/assets/44928041/7c1dfc59-823d-43eb-a9a0-86274c228373)
- "Sol Arach": Sol is listed but Sol Arach no longer
![image](https://github.com/quyykk/plugin-editor/assets/44928041/07c0cd5d-a5cd-43ce-ba3b-76ac6cf2efb6)

**Comment by quyykk** [comment]
Fixed, thanks!
